import type { Metadata } from "next";
import "@/app/globals.css";
import AdminWrapper from "./AdminWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <AdminWrapper>{children}</AdminWrapper>;
}
